pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
    - ./node_modules
    - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
  build:
    image: docker
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/jq:/usr/bin/jq
    commands:
    # - yarn global add cross-var
    # - yarn docker.build
    # - export IMAGENAME=$(jq '.config.imageRepo + ":" + .version' < package.json)
    # - docker image build -t $IMAGENAME .
    - export IMAGE-REPO=$(jq '.config.imageRepo' < package.json)
    - export IMAGE-TAG=$(jq '.version' < package.json)
    - docker image build -t $IMAGE-REPO:$IMAGE-TAG .
    - docker image tag $IMAGE-REPO:$IMAGE-TAG $IMAGE-REPO:latest
    - docker push $IMAGE-REPO:$IMAGE-TAG
    - docker push $IMAGE-REPO:latest
  # docker:
  #   image: plugins/docker
  #   repo: rsf71/dronetest
  #   tags: latest
  #   secrets: [docker_username, docker_password]
  # publish:
  #   image: plugins/npm
  #   when:
  #     branch: master
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
