pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
    - ./node_modules
    - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
  build:
    image: node:10-alpine
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    # - yarn install --prefer-offline
    - yarn global add cross-var
    - yarn docker.build
    - docker push rsf71/testdrone
  # docker:
  #   image: plugins/docker
  #   repo: rsf71/dronetest
  #   tags: latest
  #   secrets: [docker_username, docker_password]
  # publish:
  #   image: plugins/npm
  #   when:
  #     branch: master
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
