pipeline:
  # build:
  #   image: node:10-alpine
  #   commands:
  #   - yarn install
  #   - yarn test
  docker:
    image: plugins/docker
    repo: rsf71/dronetest
    tags: latest
    secrets: [docker_username, docker_password]
    # publish:
    #   image: plugins/npm
    #   when:
    #     branch: master