pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    privileged: true
    mount:
      - ./.git
      - ./node_modules
      - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
  install:
    image: node:10-alpine
    privileged: true
    commands:
      - apk add --no-cache git openssh-client ca-certificates
      # - echo $SSH_KEY | ssh-add -
      - echo "-----START-----"
      - echo $SSH_KEY
      - echo "-----END-----"
      - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - ssh-keyscan bitbucket.org > ~/.ssh/known_hosts
      - yarn install --prefer-offline
      - yarn build
      - yarn test
    when:
      event: [push, pull_request, tag]
  build-server:
    group: build
    image: plugins/docker
    repo: rsf71/dronetest-server
    dockerfile: Dockerfile-server
    tag:
      - latest
      - ${DRONE_TAG}
    # auto_tag: true
    # storage_path: /drone/docker
    secrets: [docker_username, docker_password]
    when:
      event: tag
  build-db:
    group: build
    image: plugins/docker
    repo: rsf71/dronetest-db
    dockerfile: Dockerfile-db
    # auto_tag: true
    tag:
      - latest
      - ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      event: tag
  deploy:
    image: komljen/drone-kubectl-helm
    secrets: [kubernetes_server, kubernetes_cert, kubernetes_token]
    # environment:
    #   - TAG=$$TAG
    helm: upgrade --install --set tag=${DRONE_TAG} --namespace test testdrone charts/testdrone --debug
    when:
      event: deployment
  # helm_deploy:
  #   image: quay.io/ipedrazas/drone-helm
  #   skip_tls_verify: true
  #   chart: ./helm/testdrone
  #   release: dronetest
  #   namespace: test
  #   secrets: [prod_api_server, prod_kubernetes_token]
  #   debug: true
  rebuild-cache:
    image: drillster/drone-volume-cache
    privileged: true
    rebuild: true
    mount:
      - ./.git
      - ./node_modules
      - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
