pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    privileged: true
    mount:
    - ./.git
    - ./node_modules
    - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
  # docker:
  #   image: rsf71/docker
  #   privileged: true
  #   pull: true
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   secrets: [docker_username, docker_password]
  # gcr:
  #   image: rsf71/docker
  #   privileged: true
  #   pull: true
  #   registry: us.gcr.io
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   secrets: [docker_username, docker_password]
  docker:
    image: plugins/docker
    repo: rsf71/dronetest
    tags: latest
    secrets: [docker_username, docker_password]
  # publish:
  #   image: plugins/npm
  #   when:
  #     branch: master
  rebuild-cache:
    image: drillster/drone-volume-cache
    privileged: true
    rebuild: true
    mount:
    - ./.git
    - ./node_modules
    - ./npm-packages-offline-cache
    volumes:
    - /tmp/cache:/cache
