pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    privileged: true
    mount:
      - ./.git
      - ./node_modules
      - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
  install:
    image: node:10-alpine
    privileged: true
    commands:
      - yarn install --prefer-offline
      - yarn build
      - yarn test
  build-server:
    group: build
    image: plugins/docker
    repo: rsf71/dronetest-server
    dockerfile: Dockerfile-server
    auto_tag: true
    # storage_path: /drone/docker
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag
  build-db:
    group: build
    image: plugins/docker
    repo: rsf71/dronetest-db
    dockerfile: Dockerfile-db
    auto_tag: true
    secrets: [docker_username, docker_password]
  deploy:
    image: komljen/drone-kubectl-helm
    secrets: [kubernetes_server, kubernetes_cert, kubernetes_token]
    helm: upgrade --install --namespace test testdrone helm/testdrone --debug
  # helm_deploy:
  #   image: quay.io/ipedrazas/drone-helm
  #   skip_tls_verify: true
  #   chart: ./helm/testdrone
  #   release: dronetest
  #   namespace: test
  #   secrets: [prod_api_server, prod_kubernetes_token]
  #   debug: true
  rebuild-cache:
    image: drillster/drone-volume-cache
    privileged: true
    rebuild: true
    mount:
      - ./.git
      - ./node_modules
      - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
