pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
    - ./.git
    - ./node_modules
    - ./npm-packages-offline-cache
    volumes:
      - /tmp/cache:/cache
  build:
    image: rsf71/docker
    pull: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    # - /usr/bin/jq:/usr/bin/jq
    commands:
    - echo $(jq -r '.config.imageRepo' < package.json)
    - export IMAGE_REPO=$(jq -r '.config.imageRepo' < package.json)
    - export IMAGE_TAG=$(jq -r '.version' < package.json)
    - docker image build -t $IMAGE_REPO:$IMAGE_TAG .
    - docker image tag $IMAGE_REPO:$IMAGE_TAG $IMAGE_REPO:latest
    - docker push $IMAGE_REPO:$IMAGE_TAG
    - docker push $IMAGE_REPO:latest
    secrets: [docker_username, docker_password]
  # docker:
  #   image: plugins/docker
  #   repo: rsf71/dronetest
  #   tags: latest
  #   secrets: [docker_username, docker_password]
  # publish:
  #   image: plugins/npm
  #   when:
  #     branch: master
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
    - ./.git
    - ./node_modules
    - ./npm-packages-offline-cache
    volumes:
    - /tmp/cache:/cache
