###########################################
FROM node:10-alpine
###########################################

ARG HOME=${HOME:-/home/node}

RUN mkdir -p $HOME/app

WORKDIR $HOME/app

COPY node_modules ./node_modules

COPY package.json yarn.lock .yarnrc ./
COPY server/package.json ./server/
COPY client/package.json ./client/

COPY client/build ./client/build
COPY server ./server

WORKDIR ./server

# VOLUME $HOME/app/cache
ENTRYPOINT ["yarn", "start"]

EXPOSE 8080
