---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-db
  labels:
    name: {{.Release.Name}}-db
spec:
  type: LoadBalancer
  ports:
    - name: arango
      protocol: TCP
      port: 8529
      targetPort: 8529
  selector:
    name: {{.Release.Name}}-db
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.Release.Name}}-db
spec:
  selector:                                                                                                                                     
    matchLabels:                                                                                                                                
      name: {{.Release.Name}}-db
  replicas: 1
  template:
    metadata:
      name: {{.Release.Name}}-db
      labels: 
        name: {{.Release.Name}}-db
    spec:
     containers:
        - name: {{.Release.Name}}-db
          image: rsf71/dronetest-db:{{.Values.tag}}
          ports:
           - containerPort: 8529
          env:
          - name: ARANGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: arango-root-password