---
kind: Service
apiVersion: v1
metadata:
  name: ${NAME}
  labels:
    name: ${NAME}
spec:
  type: LoadBalancer
  ports:
    - name: arango
      protocol: TCP
      port: 8529
      targetPort: 8529
  selector:
    name: ${NAME}
---
# kind: Deployment
# apiVersion: extensions/v1beta1
# metadata:
#   name: ${NAME}
# spec:
#   replicas: 1
#   template:
#     metadata:
#       name: ${NAME}
#       labels: 
#         name: ${NAME}
#     spec:
#      containers:
#         - name: ${NAME}
#           image: rsf71/arangodb
#           ports:
#            - containerPort: 8529
#           env:
#           - name: ARANGO_ROOT_PASSWORD
#             value: password